general {
  border_size = 2
  gaps_out = 10
  col.inactive_border = rgba(595959aa)
  col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
  layout = master
  resize_on_border = true
}

input {
  numlock_by_default = true
  accel_profile = flat
}

misc {
  disable_hyprland_logo = true
  force_default_wallpaper = 0
  vrr = 2
  mouse_move_enables_dpms = true
  key_press_enables_dpms = true
  enable_swallow = true
  swallow_regex = ^(kitty)$
  background_color = 0x000000
}

binds {
  workspace_back_and_forth = true
}

opengl {
  nvidia_anti_flicker = false
  force_introspection = 0
}

cursor {
  inactive_timeout = 5
  hide_on_key_press = true
}

master {
  no_gaps_when_only = true
}

monitor=,3840x2160@120,0x0,1,bitdepth,10

bind = SUPER, Return, exec, kitty
bind = SUPER SHIFT, Q, killactive
bind = ALT, F4, killactive
bind = SUPER, Delete, exit
bind = SUPER, B, exec, firefox-developer-edition
bind = SUPER, C, exec, code
bind = SUPER, E, exec, dolphin
bind = SUPER SHIFT, Space, togglefloating
bind = SUPER, Space, exec, wofi --show drun
bind = SUPER, F, fullscreen

bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

bind = SUPER, Left, movefocus, l
bind = SUPER, Down, movefocus, d
bind = SUPER, Up, movefocus, u
bind = SUPER, Right, movefocus, r

bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, J, movewindow, d
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, L, movewindow, r

bind = SUPER SHIFT, Left, movewindow, l
bind = SUPER SHIFT, Down, movewindow, d
bind = SUPER SHIFT, Up, movewindow, u
bind = SUPER SHIFT, Right, movewindow, r

bind = SUPER, A, layoutmsg, focusmaster
bind = SUPER SHIFT, A, layoutmsg, swapwithmaster

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

bind = SUPER SHIFT, 1, movetoworkspacesilent, 1
bind = SUPER SHIFT, 2, movetoworkspacesilent, 2
bind = SUPER SHIFT, 3, movetoworkspacesilent, 3
bind = SUPER SHIFT, 4, movetoworkspacesilent, 4
bind = SUPER SHIFT, 5, movetoworkspacesilent, 5
bind = SUPER SHIFT, 6, movetoworkspacesilent, 6
bind = SUPER SHIFT, 7, movetoworkspacesilent, 7
bind = SUPER SHIFT, 8, movetoworkspacesilent, 8
bind = SUPER SHIFT, 9, movetoworkspacesilent, 9
bind = SUPER SHIFT, 0, movetoworkspacesilent, 10

bind = SUPER, S, togglespecialworkspace, scratchpad
bind = SUPER SHIFT, S, movetoworkspace, special:scratchpad

bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = workspace 1 silent, class:firefoxdeveloperedition
windowrulev2 = workspace 2 silent, class:Code, floating:0
windowrulev2 = workspace 4 silent, class:teams-for-linux
windowrulev2 = workspace 4 silent, class:discord
windowrulev2 = workspace 5 silent, class:Spotify
windowrulev2 = workspace 6 silent, class:stea 


env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/lib/pam_kwallet_init
exec-once = hypridle
exec-once = udiskie
exec-once = nm-applet
